
	<div id="tagline" class="grid_7 suffix_1 alpha omega">
		<p class="font-22 lato-strong"><strong>The power generated by the solar PV energy system at 
		our school, the EFACAP School in Lascahobas, Haiti,  
		can power 400 OLPC laptop computers. </strong>
		</p>
		<p class="font-22 lato-lite">This site shows live streaming data from our system.</p>
	</div>
	<div id="timeline" class="grid_3 alpha">
		<h3>Project Timeline</h3>
		<p><strong>February 2012</strong> <br/>
		A small team returns to EFACAP to perform solar system maintenance and install web accessible solar monitoring software.</p>
		<p><strong>December 2011</strong> <br/>
		7 students (from 3 different universities), and two mentors return to EFACAP to install improved laptop charging stations,
		setup internet connectivity and perform teacher training.  <a href="http://iitempoweringhaiti.org/project-updates">Read More...</a></p>
		<p><strong>August 2011</strong> <br/>
		Successful implementation of the world's largest single-school solar laptop charging deployment; EFACAP School, Lascahobas, Haiti</p>
		
	</div>
	<div id="slideshow" class="grid_5 omega">
		<img src="img/slideshow.jpg" />
	</div>

